# Generated by Django 5.2.9 on 2025-12-04 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_order_delivery_lat_order_delivery_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seller_lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='seller_lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
