# Generated by Django 5.2.9 on 2025-12-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_seller_lat_user_seller_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
